### ISSUE TITLE
Class "cebe\gnucash\GnuCash" not found

### ISSUE THREAD

**Issue by PeteS4** [andrewwippler/firefly_import#1]
Hi there,
I tried using your script, but unfortunately only got an error. First I ran
```
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 2 installs, 0 updates, 0 removals
  - Syncing cebe/gnucash-php (0.1.0) into cache
  - Downloading moneyphp/money (v4.1.1)
  - Installing cebe/gnucash-php (0.1.0): Cloning dev from cache
  - Installing moneyphp/money (v4.1.1): Extracting archive
Generating autoload files
```
which looks fine to me, and it creates a new directory `vendor` containing the expected files. But then in the next step I get an error:
```
$ php ./src/start.php
PHP Fatal error:  Uncaught Error: Class "cebe\gnucash\GnuCash" not found in /home/user/firefly_import/src/start.php:24
Stack trace:
#0 {main}
  thrown in /home/user/firefly_import/src/start.php on line 24
```
I have literally zero experience with PHP, so I am a bit lost here.. Some help would be greatly appreciated!

**Comment by andrewwippler** [comment]
There appears to be an issue with how php's composer is linking the library. My guess is that composer does not like the `-` in the package name.

A workaround is as follows:
Replace the contents of `vendor/composer/autoload_psr4.php` with:
```
<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Money\\' => array($vendorDir . '/moneyphp/money/src'),
    'cebe\\gnucash\\' => array($vendorDir . '/cebe/gnucash-php/src'),
    'Andrew\\FireflyImport\\' => array($baseDir . '/src'),
);
```

**Comment by tbrv** [comment]
Thanks Andrew, your comment did not solve the issue but it got me on the right track. After changing `composer.json` to add the line for `cebe\\gnucash\\` and running `composer dumpautoload` it started working:

```json
    "autoload": {
        "psr-4": {
            "Andrew\\FireflyImport\\": "src/",
            "cebe\\gnucash\\": "vendor/cebe/gnucash-php/src"
        }
    },
```

I also have no clue about PHP, so take that with a grain of salt.
